# Generated by Django 6.0.3 on 2026-08-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
