# Generated by Django 6.0.3 on 2026-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_securityevent_device_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='device_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
