# Generated by Django 6.0.3 on 2026-08-05 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_securityevent_device_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityevent',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
