# Generated by Django 6.0.3 on 2026-08-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_securityevent_login_time_securityevent_logout_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='risk_reasons',
            field=models.JSONField(default=list),
        ),
    ]
