# Generated by Django 6.0.3 on 2026-08-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_securityevent_risk_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='risk_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
