# Generated by Django 6.0.3 on 2026-08-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_securityalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='risk_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='risk_level',
            field=models.CharField(default='LOW', max_length=10),
        ),
    ]
