# Generated by Django 6.0.3 on 2026-08-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_securityevent_risk_breakdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityevent',
            name='risk_breakdown',
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20),
        ),
    ]
